package sa.techlight.kitchen;
import android.app.*;import android.content.*;import android.content.pm.ActivityInfo;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.view.*;import android.widget.*;import android.net.nsd.*;import android.util.Base64;import org.json.*;import java.net.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;import com.google.zxing.*;import com.google.zxing.common.BitMatrix;
/** Dedicated customer display: receives redacted snapshots only; never signs in to TechPro. */
public final class PickupActivity extends Activity {
    private SharedPreferences prefs;private final Handler main=new Handler(Looper.getMainLooper());private ExecutorService acceptor=Executors.newSingleThreadExecutor(),clients=new ThreadPoolExecutor(2,2,0L,TimeUnit.MILLISECONDS,new ArrayBlockingQueue<Runnable>(8));private ServerSocket server;private volatile String key,id,controller="";private volatile long expires,lastReceive,lastSequence;private String lastTest="";private volatile boolean closed,foreground;private JSONObject snapshot=new JSONObject(),config=new JSONObject();private String lastData="";private TextView networkLabel;private KitchenSound sound;private long pageTick;private Set<String> announced=new HashSet<>();private boolean baseline=true,hasPages;private NsdManager nsd;private NsdManager.RegistrationListener registration;
    private final Runnable heartbeat=new Runnable(){public void run(){if(closed)return;long age=SystemClock.elapsedRealtime()-lastReceive;if(networkLabel!=null)networkLabel.setText(controller.isEmpty()?"امسح الرمز من شاشة المطبخ / Scan from Kitchen":age>15000?"التحديث متوقف • تحقق من المطبخ / Updates paused — check Kitchen":"متصل بشاشة المطبخ / Connected to Kitchen");if(!controller.isEmpty()&&++pageTick%12==0&&hasPages)renderBoard();if(controller.isEmpty()&&System.currentTimeMillis()>expires){renew();showPair();}main.postDelayed(this,1000);}};
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);getWindow().setNavigationBarColor(0xff0d1020);getWindow().setStatusBarColor(0xff0d1020);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);prefs=getSharedPreferences("receiver",0);key=prefs.getString("key","");id=prefs.getString("id","");controller=prefs.getString("controller","");if(id.isEmpty())id=LinkCrypto.randomHex(8);if(key.isEmpty())renew();else expires=System.currentTimeMillis()+300000;
        lastSequence=prefs.getLong("lastSequence",0);lastTest=prefs.getString("lastTest","");sound=new KitchenSound(this);try{snapshot=new JSONObject(prefs.getString("snapshot","{}"));config=snapshot.optJSONObject("config");if(config==null)config=LinkStore.defaults();}catch(Exception e){snapshot=new JSONObject();try{config=LinkStore.defaults();}catch(Exception ignored){}}
        try{server=new ServerSocket();server.setReuseAddress(true);int preferred=prefs.getInt("listenPort",47040);try{server.bind(new InetSocketAddress(preferred));}catch(IOException busy){server.close();server=new ServerSocket(0);}prefs.edit().putInt("listenPort",server.getLocalPort()).apply();advertise();acceptor.execute(()->{while(!closed)try{Socket s=server.accept();s.setSoTimeout(5000);try{clients.execute(()->receive(s));}catch(RejectedExecutionException e){s.close();}}catch(Exception e){if(!closed)main.post(()->status("تعذر الاتصال المحلي / LAN error"));}});}catch(Exception e){status("تعذر بدء استقبال الشاشة / Cannot start display receiver");}
        if(controller.isEmpty())showPair();else renderBoard();main.post(heartbeat);
    }
    private void renew(){key=LinkCrypto.randomHex(32);controller="";lastSequence=0;expires=System.currentTimeMillis()+300000;prefs.edit().putString("key",key).putString("id",id).putString("controller","").remove("snapshot").remove("lastSequence").remove("lastTest").apply();snapshot=new JSONObject();lastData="";baseline=true;announced.clear();}
    private void receive(Socket socket){try(Socket s=socket){
        DataOutputStream out=new DataOutputStream(s.getOutputStream());DataInputStream in=new DataInputStream(s.getInputStream());
        String challenge=LinkCrypto.randomHex(24),secret=key;LinkCrypto.write(out,challenge.getBytes(StandardCharsets.UTF_8));
        JSONObject message=new JSONObject(LinkCrypto.open(secret,LinkCrypto.read(in)));
        if(!challenge.equals(message.optString("challenge")))throw new IOException("Replay refused");String sender=message.optString("controller");if(sender.length()<8)throw new IOException("Invalid controller");
        synchronized(this){
            if(!secret.equals(key)||(!controller.isEmpty()&&!controller.equals(sender))||(controller.isEmpty()&&System.currentTimeMillis()>expires))throw new IOException("Pairing expired or controller mismatch");
            if(message.optString("command").equals("revoke")){LinkCrypto.write(out,LinkCrypto.seal(secret,new JSONObject().put("ok",true).put("challenge",challenge).toString()));main.post(()->{renew();showPair();});return;}
            long sequence=message.optLong("sequence",0);
            if(sequence>0&&sequence<lastSequence){LinkCrypto.write(out,LinkCrypto.seal(secret,new JSONObject().put("ok",false).put("error","تحديث أقدم — تم تجاهله لحماية الطلبات").put("challenge",challenge).toString()));return;}
            JSONObject clean=new JSONObject().put("tickets",message.optJSONArray("tickets")).put("providers",message.optJSONArray("providers")).put("config",message.optJSONObject("config")).put("eta",message.optJSONObject("eta")).put("training",message.optBoolean("training"));
            String json=clean.toString();
            if(!prefs.edit().putString("controller",sender).putString("key",secret).putString("id",id).putString("snapshot",json).putLong("lastSequence",Math.max(lastSequence,sequence)).commit())throw new IOException("Cannot persist display snapshot");
            controller=sender;lastSequence=Math.max(lastSequence,sequence);
            FutureTask<Integer> draw=new FutureTask<>(()->{
                if(closed)throw new IOException("Display closed");snapshot=clean;config=clean.optJSONObject("config");if(config==null)config=LinkStore.defaults();
                if(!lastData.equals(json)){notifyReady();renderBoard();lastData=json;}
                String test=config.optString("testId");if(!test.isEmpty()&&!test.equals(lastTest)){lastTest=test;prefs.edit().putString("lastTest",test).apply();showConnectionTest();}
                int count=0;JSONArray tickets=LinkStore.array(snapshot,"tickets");for(int i=0;i<tickets.length();i++){JSONObject t=tickets.optJSONObject(i);if(t!=null&&allowed(t))count++;}return count;
            });main.post(draw);int visibleCount=draw.get(5,TimeUnit.SECONDS);lastReceive=SystemClock.elapsedRealtime();
            LinkCrypto.write(out,LinkCrypto.seal(secret,new JSONObject().put("ok",true).put("sequence",lastSequence).put("visibleCount",visibleCount).put("foreground",foreground).put("challenge",challenge).toString()));
        }
        }catch(Exception ignored){/* Never log snapshots, pairing keys or public phone suffixes. */}}
    private void showConnectionTest(){
        LinearLayout panel=column();panel.setPadding(dp(45),dp(35),dp(45),dp(35));panel.setBackground(Ui.rounded(0xffe9faf2,20,this));
        panel.addView(text("✓",55,0xff168163,true));panel.addView(text("الشاشة متصلة بالمطبخ",28,0xff163b30,true));panel.addView(text("Connected to Kitchen",22,0xff163b30,true));
        panel.addView(text("اختبار اتصال فقط — ليس طلبًا\nConnection test — not an order",14,0xff456357,false));
        Dialog dialog=new Dialog(this);dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);dialog.setContentView(panel);dialog.show();if(dialog.getWindow()!=null)dialog.getWindow().setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));main.postDelayed(()->{if(!isFinishing())dialog.dismiss();},4500);
    }
    private void notifyReady(){JSONArray a=LinkStore.array(snapshot,"tickets");Set<String> next=new HashSet<>();boolean fresh=false;for(int i=0;i<a.length();i++){JSONObject t=a.optJSONObject(i);if(t==null||!allowed(t))continue;String k=t.optString("id")+":"+t.optLong("announced");next.add(k);if(!announced.contains(k))fresh=true;}announced=next;if(!baseline&&fresh&&config.optBoolean("sound",true)){getSharedPreferences("premium_settings",0).edit().putBoolean("sound",true).putInt("volume",config.optInt("volume",85)).apply();sound.play(KitchenSound.READY);}baseline=false;}
    private void advertise(){try{nsd=(NsdManager)getSystemService(NSD_SERVICE);NsdServiceInfo s=new NsdServiceInfo();s.setServiceName("TL-Pickup-"+id);s.setServiceType("_tlpickup._tcp.");s.setPort(server.getLocalPort());registration=new NsdManager.RegistrationListener(){public void onServiceRegistered(NsdServiceInfo i){}public void onRegistrationFailed(NsdServiceInfo i,int e){}public void onServiceUnregistered(NsdServiceInfo i){}public void onUnregistrationFailed(NsdServiceInfo i,int e){}};nsd.registerService(s,NsdManager.PROTOCOL_DNS_SD,registration);}catch(Exception ignored){}}
    private String host(){try{Enumeration<NetworkInterface> en=NetworkInterface.getNetworkInterfaces();while(en.hasMoreElements()){NetworkInterface ni=en.nextElement();for(InetAddress a:Collections.list(ni.getInetAddresses()))if(!a.isLoopbackAddress()&&a instanceof Inet4Address&&a.isSiteLocalAddress())return a.getHostAddress();}}catch(Exception ignored){}return "127.0.0.1";}
    private int dp(float n){return Ui.dp(this,n);}private LinearLayout column(){LinearLayout p=new LinearLayout(this);p.setOrientation(1);return p;}private TextView text(String s,int size,int color,boolean bold){TextView t=Ui.text(this,s,size,color,bold);t.setGravity(Gravity.CENTER);t.setTextDirection(View.TEXT_DIRECTION_FIRST_STRONG);return t;}
    private int color(String k,String fallback){try{return Color.parseColor(config.optString(k,fallback));}catch(Exception e){return Color.parseColor(fallback);}}
    private void showPair(){setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);LinearLayout root=column();root.setBackgroundColor(0xff0d1020);root.setGravity(Gravity.CENTER);root.setPadding(dp(28),dp(18),dp(28),dp(18));root.addView(text("شاشة استلام الطلبات\nTECHLIGHT PICKUP",26,Color.WHITE,true));root.addView(text("من إعدادات المطبخ ← شاشات العملاء ← إضافة شاشة\nKitchen Settings → Pickup screens → Add screen",15,0xffacb7d1,false));try{JSONObject qr=new JSONObject().put("type","techlight-pickup-v1").put("host",host()).put("port",server==null?0:server.getLocalPort()).put("id",id).put("key",key);String code=qr.toString();BitMatrix matrix=new MultiFormatWriter().encode(code,BarcodeFormat.QR_CODE,420,420);Bitmap bitmap=Bitmap.createBitmap(420,420,Bitmap.Config.ARGB_8888);for(int y=0;y<420;y++)for(int x=0;x<420;x++)bitmap.setPixel(x,y,matrix.get(x,y)?Color.BLACK:Color.WHITE);ImageView image=new ImageView(this);image.setImageBitmap(bitmap);int q=Math.min(dp(300),getResources().getDisplayMetrics().heightPixels/2);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(q,q);lp.gravity=Gravity.CENTER;lp.setMargins(0,dp(18),0,dp(12));root.addView(image,lp);root.addView(text(host()+":"+(server==null?0:server.getLocalPort())+"  •  "+id,13,0xffacb7d1,false));Button manual=Ui.button(this,"نص الربط اليدوي / Manual pairing",0xff2a3450);root.addView(manual);manual.setOnClickListener(v->{TextView tx=new TextView(this);tx.setText(code);tx.setTextIsSelectable(true);tx.setPadding(dp(20),dp(20),dp(20),dp(20));new AlertDialog.Builder(this).setTitle("رمز خاص — لا تشاركه علنًا / Private pairing code").setView(tx).setPositiveButton("إغلاق / Close",null).show();});}catch(Exception e){root.addView(text("تعذر إنشاء QR / QR unavailable",16,0xffffba70,false));}networkLabel=text("",14,0xff37d6a0,true);root.addView(networkLabel);setContentView(root);}
    private boolean allowed(JSONObject t){String mode=config.optString("mode","split");boolean delivery=t.optString("kind").equals("delivery");return mode.equals("split")||mode.equals("all")||(mode.equals("customer")&&!delivery)||(mode.equals("delivery")&&delivery)||mode.equals(t.optString("provider"));}
    private void renderBoard(){if(closed)return;int orient=config.optInt("orientation",0);int request=orient==1?ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE:orient==2?ActivityInfo.SCREEN_ORIENTATION_PORTRAIT:orient==3?ActivityInfo.SCREEN_ORIENTATION_REVERSE_LANDSCAPE:orient==4?ActivityInfo.SCREEN_ORIENTATION_REVERSE_PORTRAIT:ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED;if(getRequestedOrientation()!=request)setRequestedOrientation(request);
        int bg=color("background","#0D1020"),fg=color("text","#F7F9FF"),accent=color("accent","#37D6A0");LinearLayout root=column();root.setBackgroundColor(bg);root.setPadding(dp(20),dp(10),dp(20),dp(10));LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);String logo=config.optString("logo");if(!logo.isEmpty()){ImageView iv=image(logo);if(iv!=null)header.addView(iv,new LinearLayout.LayoutParams(dp(120),dp(54)));}TextView title=text(config.optString("title","جاهز للاستلام / Ready for pickup"),24,fg,true);header.addView(title,new LinearLayout.LayoutParams(0,dp(56),1));header.setOnLongClickListener(v->{confirmReset();return true;});root.addView(header);
        if(snapshot.optBoolean("training"))root.addView(text("وضع تجربة — ليست طلبات حقيقية / TRAINING — NOT LIVE ORDERS",13,0xffffbb66,true));
        if(config.optBoolean("eta",true)){JSONObject eta=snapshot.optJSONObject("eta");if(eta!=null){String mode=config.optString("mode","split");JSONObject data=eta.optJSONObject(mode.equals("delivery")?"delivery":mode.equals("customer")?"customer":"all");if(data!=null){LinearLayout panel=column();panel.setPadding(dp(12),dp(8),dp(12),dp(8));panel.setBackground(Ui.outlined(color("card","#1A2034"),accent,14,this));panel.addView(text("الوقت المتوقع لاستلام الطلب الجديد  |  Estimated pickup time for new orders",14,fg,true));panel.addView(text("حوالي "+data.optInt("minutes",12)+" دقيقة   •   About "+data.optInt("minutes",12)+" minutes",25,accent,true));panel.addView(text(data.optBoolean("fallback")?"وقت افتراضي تقديري — لا توجد عينة كافية / Default estimate — not enough data":"متوسط آخر "+data.optInt("samples")+" طلبًا • حتى الجاهزية / Average of last "+data.optInt("samples")+" orders • until ready",11,fg,false));root.addView(panel,new LinearLayout.LayoutParams(-1,-2));}}}
        hasPages=false;List<JSONObject> customers=new ArrayList<>(),delivery=new ArrayList<>();JSONArray a=LinkStore.array(snapshot,"tickets");for(int i=0;i<a.length();i++){JSONObject t=a.optJSONObject(i);if(t!=null&&allowed(t)){if(t.optString("kind").equals("delivery"))delivery.add(t);else customers.add(t);}}
        LinearLayout sections=new LinearLayout(this);boolean portrait=getResources().getConfiguration().screenWidthDp<getResources().getConfiguration().screenHeightDp;sections.setOrientation(portrait?1:0);String mode=config.optString("mode","split");if(mode.equals("split")){sections.addView(section("العملاء / Customers",customers),new LinearLayout.LayoutParams(portrait?-1:0,portrait?0:-1,1));sections.addView(section("تطبيقات التوصيل / Delivery apps",delivery),new LinearLayout.LayoutParams(portrait?-1:0,portrait?0:-1,1));}else{List<JSONObject> all=new ArrayList<>(customers);all.addAll(delivery);sections.addView(section(mode.equals("customer")?"العملاء / Customers":mode.equals("delivery")?"طلبات التوصيل / Delivery orders":"جاهز الآن / Ready now",all),new LinearLayout.LayoutParams(-1,-1));}root.addView(sections,new LinearLayout.LayoutParams(-1,0,1));networkLabel=text("",12,accent,false);root.addView(networkLabel,new LinearLayout.LayoutParams(-1,dp(25)));setContentView(root);
    }
    private LinearLayout section(String title,List<JSONObject> tickets){int fg=color("text","#F7F9FF"),accent=color("accent","#37D6A0");LinearLayout p=column();p.setPadding(dp(6),dp(7),dp(6),dp(4));p.addView(text(title+"  ·  "+tickets.size(),18,fg,true),new LinearLayout.LayoutParams(-1,dp(38)));if(tickets.isEmpty()){TextView empty=text("سيظهر رقمك عند جاهزية طلبك\nYour number appears when your order is ready",18,fg,false);p.addView(empty,new LinearLayout.LayoutParams(-1,0,1));return p;}
        int cols=Math.max(1,Math.min(5,config.optInt("columns",3)));if(config.optString("mode").equals("split"))cols=Math.min(2,cols);int capacity=cols*2,pages=(tickets.size()+capacity-1)/capacity,page=(int)(pageTick/12)%Math.max(1,pages),index=page*capacity;for(int row=0;row<2;row++){LinearLayout line=new LinearLayout(this);p.addView(line,new LinearLayout.LayoutParams(-1,0,1));for(int c=0;c<cols;c++){FrameLayout slot=new FrameLayout(this);slot.setPadding(dp(4),dp(4),dp(4),dp(4));line.addView(slot,new LinearLayout.LayoutParams(0,-1,1));if(index>=tickets.size())continue;JSONObject t=tickets.get(index++);LinearLayout card=column();card.setGravity(Gravity.CENTER);card.setPadding(dp(10),dp(8),dp(10),dp(8));card.setBackground(Ui.outlined(color("card","#1A2034"),accent,17,this));JSONObject provider=provider(t.optString("provider"));if(provider!=null){ImageView logo=image(provider.optString("logo"));if(logo!=null)card.addView(logo,new LinearLayout.LayoutParams(dp(90),dp(40)));card.addView(text(provider.optString("name"),12,fg,true));}else card.addView(text(t.optString("kind").equals("phone")?"آخر ٧ أرقام من الجوال / Last 7 phone digits":"رقم الفاتورة / Invoice number",11,fg,false));TextView number=text(t.optString("number"),Math.max(28,Math.min(110,config.optInt("numberSize",54))),fg,true);number.setTextDirection(View.TEXT_DIRECTION_LTR);number.setSingleLine(true);if(Build.VERSION.SDK_INT>=26)number.setAutoSizeTextTypeUniformWithConfiguration(22,Math.max(28,Math.min(110,config.optInt("numberSize",54))),2,android.util.TypedValue.COMPLEX_UNIT_SP);card.addView(number,new LinearLayout.LayoutParams(-1,0,1));card.addView(text("جاهز الآن / Ready now",12,accent,true));slot.addView(card,new FrameLayout.LayoutParams(-1,-1));}}
        if(pages>1)hasPages=true;if(pages>1)p.addView(text((page+1)+" / "+pages,11,fg,false));return p;}
    private JSONObject provider(String id){if(id.isEmpty())return null;JSONArray a=LinkStore.array(snapshot,"providers");for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);if(p!=null&&p.optString("id").equals(id))return p;}return null;}
    private ImageView image(String b64){if(b64.isEmpty()||b64.length()>350000)return null;try{byte[] b=Base64.decode(b64,Base64.DEFAULT);Bitmap bitmap=BitmapFactory.decodeByteArray(b,0,b.length);if(bitmap==null)return null;ImageView i=new ImageView(this);i.setImageBitmap(bitmap);i.setScaleType(ImageView.ScaleType.CENTER_INSIDE);return i;}catch(Exception e){return null;}}
    private void status(String s){if(networkLabel!=null)networkLabel.setText(s);}
    private void confirmReset(){EditText pin=new EditText(this);pin.setInputType(18);AlertDialog d=new AlertDialog.Builder(this).setTitle("فصل الشاشة / Unpair display").setMessage("أدخل رمز إدارة الشاشة / Enter display manager PIN").setView(pin).setPositiveButton("فصل / Unpair",null).setNegativeButton("إلغاء / Cancel",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(x->{String expected=config.optString("pinHash",Session.hash("0000"));if(Session.hash(pin.getText().toString()).equals(expected)){d.dismiss();renew();showPair();}else pin.setError("رمز غير صحيح / Incorrect PIN");}));d.show();}
    @Override protected void onResume(){super.onResume();foreground=true;}
    @Override protected void onPause(){foreground=false;super.onPause();}
    @Override public void onConfigurationChanged(android.content.res.Configuration c){super.onConfigurationChanged(c);main.post(()->{if(controller.isEmpty())showPair();else renderBoard();});}
    @Override public void onBackPressed(){confirmReset();}
    @Override protected void onDestroy(){closed=true;main.removeCallbacksAndMessages(null);try{if(server!=null)server.close();}catch(Exception ignored){}acceptor.shutdownNow();clients.shutdownNow();if(sound!=null)sound.release();if(nsd!=null&&registration!=null)try{nsd.unregisterService(registration);}catch(Exception ignored){}super.onDestroy();}
}
